const profileData = {
    login: 'subh3ndu',
    id: 116610837,
    node_id: 'U_kgDOBvNXFQ',
    avatar_url: 'https://avatars.githubusercontent.com/u/116610837?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/subh3ndu',
    html_url: 'https://github.com/subh3ndu',
    followers_url: 'https://api.github.com/users/subh3ndu/followers',
    following_url:
        'https://api.github.com/users/subh3ndu/following{/other_user}',
    gists_url: 'https://api.github.com/users/subh3ndu/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/subh3ndu/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/subh3ndu/subscriptions',
    organizations_url: 'https://api.github.com/users/subh3ndu/orgs',
    repos_url: 'https://api.github.com/users/subh3ndu/repos',
    events_url: 'https://api.github.com/users/subh3ndu/events{/privacy}',
    received_events_url:
        'https://api.github.com/users/subh3ndu/received_events',
    type: 'User',
    site_admin: false,
    name: 'Subhendu Karmakar',
    company: 'Indira Gandhi Institute of Technology, Sarang',
    blog: 'https://subhendu.vercel.app',
    location: 'Odisha, India',
    email: null,
    hireable: null,
    bio: 'hehe...\r\n',
    twitter_username: 'SubhenduKarma',
    public_repos: 70,
    public_gists: 0,
    followers: 2,
    following: 13,
    created_at: '2022-10-25T01:19:50Z',
    updated_at: '2022-12-24T10:48:00Z',
};

export default profileData;
